class Settings(object):
    SCREEN_WIDTH = 1300
    SCREEN_HEIGHT = 800
    SCREEN_MID_X = SCREEN_WIDTH // 2
    SCREEN_MID_Y = SCREEN_HEIGHT // 2
    SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

    FPS = 60

    BACKGROUND_COLOR = 79, 142, 186
