class Settings(object):
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    SCREEN_MID_X = SCREEN_WIDTH // 2
    SCREEN_MID_Y = SCREEN_HEIGHT // 2
    SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

    FPS = 60

    BACKGROUND_COLOR = 255, 255, 255
